variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
  - build
  - test
  - package
  - deploy

build_job:
  stages: build
  tags:
    - docker
  script:
    - echo "Maven compile started"
    - "mvm compile"